name: Minecraft AFK Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Mineflayer
        run: npm install mineflayer prismarine-auth

      # Пробуем скачать сохраненную сессию из артефактов
      - name: Download Session
        uses: dawidd6/action-download-artifact@v3
        with:
          name: mcc-session
          path: ./nmp-cache
          if_no_artifact_found: warn

      - name: Create Bot Script
        run: |
          cat << EOF > bot.js
          const mineflayer = require('mineflayer')
          const bot = mineflayer.createBot({
            host: process.env.SERVER_IP,
            auth: 'microsoft',
            profilesFolder: './nmp-cache'
          })

          bot.on('login', () => {
            console.log('Успех! Бот залогинился.')
            // Как только залогинились - создаем файл-маяк для сохранения
            const fs = require('fs')
            fs.writeFileSync('logged_in.txt', 'true')
          })
          
          bot.on('spawn', () => console.log('Персонаж в игре.'))
          
          bot.on('microsoftAuth', (info) => {
            console.log('------------------------------------------')
            console.log('ПЕРЕЙДИ СЮДА:', info.user_code_url)
            console.log('ВВЕДИ ЭТОТ КОД:', info.user_code)
            console.log('------------------------------------------')
          })
          EOF

      - name: Run Bot
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: node bot.js & sleep 300 # Запускаем в фоне на 5 минут для теста или просто node bot.js

      # Сохраняем сессию в любом случае, даже если бот был убит
      - name: Save Session
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mcc-session
          path: ./nmp-cache
          retention-days: 1
