name: Minecraft AFK Bot
on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          repository: MC-Console-Client/Minecraft-Console-Client
          ref: master

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build and Run
        run: |
          cd MinecraftClient
          dotnet run -- "${{ secrets.MC_LOGIN }}" Microsoft "${{ secrets.SERVER_IP }}"
